blog_site/blog/urls.py
from django.urls import path
from .views import HomeListView
from . import views

app_name = "blog"
urlpatterns = [
    path("", HomeListView.as_view(), name="home"),
    path("topic/<slug:slug>/", views.topic_list_view, name="topic_list"),
    path("create_test/", views.create_test_topics, name="create_test"),
    path("create/", views.page_create_view, name="create"),
    path("<slug:slug>/", views.page_view, name="page"),
    path("search/", views.search_view, name="search"),
]
# PAGE ID CHANGED TO SLUG

blog_site/blog_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("html_gen/", include("html_generator.urls")),
    path("auth/", include("login_app.urls")),
    path("", include("blog.urls")),
]

blog_site/blog/models.py
from django.db import models

# Create your models here.

blog_site/blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic import ListView
from django.utils import timezone
from django.apps import apps
from django.db.models import Q
from django.contrib.auth.decorators import login_required
import markdown




class HomeListView(ListView):
    def __init__(self):
        super().__init__()
        self.model = apps.get_model("html_generator", "HtmlModel")
        self.template_name = "index.html"

    def get(self, request):
        search_string = request.GET.get("search")

        HtmlModel = apps.get_model("html_generator", "HtmlModel")
        TopicModel = apps.get_model("html_generator", "TopicModel")

        topic_list = TopicModel.objects.all()

        if search_string:
            filtered_list = HtmlModel.objects.filter(Q(title__icontains=search_string) | Q(description__icontains=search_string))
            context = { "filtered_list": filtered_list, "topic_list": topic_list }
            return render(request, "search.html", context)
        else:
            recommended_list = get_list_or_404(HtmlModel, featured=True)
            lastest_list = HtmlModel.objects.order_by('-pub_date')[:4]
            context = { "topic_list": topic_list, "recommended_list": recommended_list, "latest_post_list": lastest_list }
            return render(request, "index.html", context)
        

@login_required
def page_create_view(request):
    return HttpResponseRedirect(reverse("html_generator:html_gen"))

def page_view(request, slug):
    HtmlModel = apps.get_model("html_generator", "HtmlModel")
    html_object = get_object_or_404(HtmlModel,slug=slug)
    context = { "html_page": html_object.page }
    return render(request, "page.html", context)

def search_view(request):
    search_string = request.GET.get("search")

    if search_string:
        HtmlModel = apps.get_model("html_generator", "HtmlModel")
        filtered_list = HtmlModel.objects.filter(Q(title__icontains=search_string) | Q(description__icontains=search_string))
        context = { "filtered_list": filtered_list }
        return render(request, "search.html", context)
    else:
        return HttpResponseRedirect(reverse("blog:index"))

def topic_list_view(request, slug):
    TopicModel = apps.get_model("html_generator", "TopicModel")
    HtmlModel = apps.get_model("html_generator", "HtmlModel")

    topic_page = get_object_or_404(TopicModel, slug=slug)
    topic_pages = HtmlModel.objects.filter(topics__in=[topic_page])

    context = { "topic_pages": topic_pages }

    return render(request, "topic_list.html", context)

def create_test_pages(request):
    titles = ["test t1", "test t2", "test t3", "test t4", "test t5", "test t6"]
    descriptions = ["test d1", "test d2", "test d3", "test d4", "test d5", "test d6"]
    bodys = ["## test b1\n- testing\n- testing", "## test b2\n- testing\n- testing", "## test b3\n- testing\n- testing", "## test b4\n- testing\n- testing", "## test b5\n- testing\n- testing", "## test b6\n- testing\n- testing", ]
    
    for c in range(6):
        title = titles[c]
        description= descriptions[c]
        body = bodys[c]

        MarkdownModel = apps.get_model("html_generator", "MarkdownModel")
        md_object = MarkdownModel.objects.create(user=request.user, title=title, description=description, body=body, pub_date=timezone.now())
        md_object.save()
        md_object.refresh_from_db()
        page = f"# {title}\n{body}"

        slug = str(title).replace(" ", "_")

        html = markdown.markdown(page)

        HtmlModel = apps.get_model("html_generator", "HtmlModel")
        html_object = HtmlModel.objects.create(user=request.user, mdModel=md_object, title=title, description=description, page=html, slug=slug, pub_date=timezone.now())
        html_object.save()
        html_object.refresh_from_db()
    return HttpResponse("View Ran Successfully")

def create_test_topics(request):
    TopicModel = apps.get_model("html_generator", "TopicModel")
    HtmlModel = apps.get_model("html_generator", "HtmlModel")


    linux_topic = TopicModel.objects.create(title="Linux", slug="Linux")
    fast_api_topic = TopicModel.objects.create(title="Fast API", slug="Fast Api")
    django_topic = TopicModel.objects.create(title="Django", slug="Django")

    linux_topic.save()
    fast_api_topic.save()
    django_topic.save()

    linux_topic.refresh_from_db()
    fast_api_topic.refresh_from_db()
    django_topic.refresh_from_db()

    page = get_object_or_404(HtmlModel, pk=1)

    page.topics.add(linux_topic, django_topic)

    return HttpResponse("View Ran Successfully")

blog_site/blog/templates/base.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>Blogpad</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'base.css' %}">

</head>
<body>

{% block header %}
<header>
  <h1>Blogpad</h1>
  <div id="header-stack">
  <form id="form" role="search" action="{% url 'blog:home' %}">
    <input id="search-bar" type="search" id="query" name="search"
    placeholder="Search..."
    aria-label="Search through site content">
    <button>Search</button>
  </form>
    <!-- <a>
      Login/Register
    </a> -->
  </div>  
</header>
{% endblock %}

{%block content%}
{% endblock %}
</body>
</html>

blog_site/blog/templates/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% extends 'base.html' %}
  <meta charset="UTF-8">
  <title>Blogpad Home</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
<!-- partial:index.partial.html -->
{% block content %}
<div class="section-box">
<section id="intro" class="home-section">
  <h2>Welcome To Blogpad</h2>
  <p>This is my blogging website intended for journals and tutorials under the topic of technology.</p>
  <p>You can select a published titlr or topic below and go to that page or search then do the same</p>
</section>

<section class="home-section">
  <h2>Topics</h2>
  <div class="post-cont">
  {% for topic in topic_list %}
  <article class="post-box">
    <a class="post-box-link" href="{% url 'blog:topic_list' topic.slug %}"><p class="post-box-description">{{ topic }}</p></a>
  </article>
  {% endfor %}
  </div>
</section>

<section id="post" class="home-section">
  <h2>Latest Pages</h2>
  <div class="post-cont">
  {% for post in latest_post_list %}
  {% if forloop.counter <= 4 %}
  <!-- add descriptions to post models and place them in html post box instead of page -->
  <article class="post-box">
  <a class="post-box-link" href="{% url 'blog:page' post.slug %}">
    <h4 class="post-box-title">{{ post.title | safe }}</h4>
    <p>Description:<p>
    <p class="post-box-description">{{ post.description | safe }}</p>
  </a>
  </article>
  {% endif %}
  {% endfor %}
  </div>
</section>

<section class="home-section">
  <h2>Recommended Pages</h2>
  <div class="post-cont">
  {% for post in  recommended_list%}
  {% if forloop.counter <= 4 %}
  <!-- add descriptions to post models and place them in html post box instead of page -->
  <article class="post-box">
  <a class="post-box-link" href="{% url 'blog:page' post.slug %}">
    <h4 class="post-box-title">{{ post.title | safe }}</h4>
    <p>Description:<p>
    <p class="post-box-description">{{ post.description | safe }}</p>
  </a>
  </article>
  {% endif %}
  {% endfor %}
  </div>
</section>
</div>
{% endblock %}
<!-- partial -->
  
</body>
</html>

blog_site/blog/templates/login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% extends 'base.html' %}
  <meta charset="UTF-8">
  <title>Blogpad Login</title>
  {% load static %}
</head>
<body>
{% block content %}
<link rel="stylesheet" href="{% static 'login.css' %}">
<div id="outer-container">
<div id="login-container">
  <form id="login-form">
    <h2 id="login-title">Login</h2>
    <input id="username-input" class="text-input" type="text" placeholder="Username"/>
    <input id="password-input" class="text-input" type="password" placeholder="Password"/>
    <input id="submit-button" type="submit" value="Login"/>
    <a id="register-link" href="#">
    Not registered? Create Account!
    </a>
  </form>

  <form id="register-form">
    <h2 id="register-title">Create Account</h2>
    <input type="email" class="text-input" placeholder="email"/>
    <input id="username-input" class="text-input" type="text" placeholder="Username"/>
    <input id="password-input" class="text-input" type="password" placeholder="Password"/>
    <input id="password-input" class="text-input" type="password" placeholder="Re-enter Password"/>
    <input id="submit-button" type="submit" value="register"/>
    <a id="login-link" href="#">
      Already registered? Login!
    </a>
  </form>
</div>
</div>
<script  src="{% static 'login.js' %}"></script>

{% endblock %}
</body>
</html>

blog_site/blog/templates/markdown_form.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% extends 'base.html' %}
  <meta charset="UTF-8">
  <title>Blogpad Home</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}
</body>

blog_site/blog/templates/page.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% extends 'base.html' %}
  <meta charset="UTF-8">
  <title>Blogpad Page</title>
  {% load static %}
</head>
<body>
{% block content %}
<link rel="stylesheet" href="{% static 'page.css' %}">
<article id="page-article">
{{ html_page | safe }}
</article>
{% endblock %}
</body>

blog_site/blog/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'search.css' %}">
<article class="search-list">
{% for page in filtered_list %}
<section class="page-section">
    <a href="{% url 'blog:page' page.slug %}">
        <h3>{{ page.title }}</h3>
        <p>{{ page.description }}</p>
    </a>
</section>
{% endfor %}
</article>
{% endblock %}

blog_site/blog/templates/topic_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'search.css' %}">
<article class="search-list">
{% for page in topic_pages %}
<section class="page-section">
    <a href="{% url 'blog:page' page.slug %}">
        <h3>{{ page.title }}</h3>
        <p>{{ page.description }}</p>
    </a>
</section>
{% endfor %}
</article>
{% endblock %}